// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/core.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendDataRequest struct {
	NumMessages          int32    `protobuf:"varint,1,opt,name=num_messages,json=numMessages,proto3" json:"num_messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendDataRequest) Reset()         { *m = SendDataRequest{} }
func (m *SendDataRequest) String() string { return proto.CompactTextString(m) }
func (*SendDataRequest) ProtoMessage()    {}
func (*SendDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b0acae2797acdd, []int{0}
}

func (m *SendDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendDataRequest.Unmarshal(m, b)
}
func (m *SendDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendDataRequest.Marshal(b, m, deterministic)
}
func (m *SendDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendDataRequest.Merge(m, src)
}
func (m *SendDataRequest) XXX_Size() int {
	return xxx_messageInfo_SendDataRequest.Size(m)
}
func (m *SendDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendDataRequest proto.InternalMessageInfo

func (m *SendDataRequest) GetNumMessages() int32 {
	if m != nil {
		return m.NumMessages
	}
	return 0
}

type QuotationRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuotationRequest) Reset()         { *m = QuotationRequest{} }
func (m *QuotationRequest) String() string { return proto.CompactTextString(m) }
func (*QuotationRequest) ProtoMessage()    {}
func (*QuotationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b0acae2797acdd, []int{1}
}

func (m *QuotationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuotationRequest.Unmarshal(m, b)
}
func (m *QuotationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuotationRequest.Marshal(b, m, deterministic)
}
func (m *QuotationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuotationRequest.Merge(m, src)
}
func (m *QuotationRequest) XXX_Size() int {
	return xxx_messageInfo_QuotationRequest.Size(m)
}
func (m *QuotationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuotationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuotationRequest proto.InternalMessageInfo

func (m *QuotationRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type QuotationNotify struct {
	Price                float32  `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuotationNotify) Reset()         { *m = QuotationNotify{} }
func (m *QuotationNotify) String() string { return proto.CompactTextString(m) }
func (*QuotationNotify) ProtoMessage()    {}
func (*QuotationNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b0acae2797acdd, []int{2}
}

func (m *QuotationNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuotationNotify.Unmarshal(m, b)
}
func (m *QuotationNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuotationNotify.Marshal(b, m, deterministic)
}
func (m *QuotationNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuotationNotify.Merge(m, src)
}
func (m *QuotationNotify) XXX_Size() int {
	return xxx_messageInfo_QuotationNotify.Size(m)
}
func (m *QuotationNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_QuotationNotify.DiscardUnknown(m)
}

var xxx_messageInfo_QuotationNotify proto.InternalMessageInfo

func (m *QuotationNotify) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *QuotationNotify) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SendDataResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendDataResponse) Reset()         { *m = SendDataResponse{} }
func (m *SendDataResponse) String() string { return proto.CompactTextString(m) }
func (*SendDataResponse) ProtoMessage()    {}
func (*SendDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b0acae2797acdd, []int{3}
}

func (m *SendDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendDataResponse.Unmarshal(m, b)
}
func (m *SendDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendDataResponse.Marshal(b, m, deterministic)
}
func (m *SendDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendDataResponse.Merge(m, src)
}
func (m *SendDataResponse) XXX_Size() int {
	return xxx_messageInfo_SendDataResponse.Size(m)
}
func (m *SendDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendDataResponse proto.InternalMessageInfo

func (m *SendDataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SendDataRequest)(nil), "SendDataRequest")
	proto.RegisterType((*QuotationRequest)(nil), "QuotationRequest")
	proto.RegisterType((*QuotationNotify)(nil), "QuotationNotify")
	proto.RegisterType((*SendDataResponse)(nil), "SendDataResponse")
}

func init() { proto.RegisterFile("proto/core.proto", fileDescriptor_a4b0acae2797acdd) }

var fileDescriptor_a4b0acae2797acdd = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0x2f, 0x4a, 0xd5, 0x03, 0x33, 0x95, 0x4c, 0xb8, 0xf8, 0x83, 0x53, 0xf3,
	0x52, 0x5c, 0x12, 0x4b, 0x12, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x14, 0xb9, 0x78,
	0xf2, 0x4a, 0x73, 0xe3, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x8b, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x58, 0x83, 0xb8, 0xf3, 0x4a, 0x73, 0x7d, 0xa1, 0x42, 0x4a, 0x3a, 0x5c, 0x02, 0x81, 0xa5,
	0xf9, 0x25, 0x89, 0x25, 0x99, 0xf9, 0x79, 0x30, 0x6d, 0x12, 0x5c, 0xec, 0x50, 0x2d, 0x60, 0x1d,
	0x9c, 0x41, 0x30, 0xae, 0x92, 0x23, 0x17, 0x3f, 0x5c, 0xb5, 0x5f, 0x7e, 0x49, 0x66, 0x5a, 0xa5,
	0x90, 0x08, 0x17, 0x6b, 0x41, 0x51, 0x66, 0x32, 0x44, 0x29, 0x53, 0x10, 0x84, 0x83, 0x6c, 0x04,
	0x13, 0xaa, 0x11, 0x3a, 0x5c, 0x02, 0x08, 0x67, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0xe2, 0xb6,
	0xd0, 0xa8, 0x8a, 0x8b, 0x37, 0xb8, 0xa4, 0x28, 0x35, 0x31, 0xd7, 0xb5, 0x22, 0x31, 0xb7, 0x20,
	0x27, 0x55, 0xc8, 0x90, 0x8b, 0x03, 0xa6, 0x5d, 0x48, 0x40, 0x0f, 0xcd, 0xc3, 0x52, 0x82, 0x7a,
	0xe8, 0x66, 0x1b, 0x30, 0x0a, 0x99, 0x71, 0xf1, 0x82, 0x44, 0xe1, 0x0e, 0x17, 0x12, 0xd4, 0x43,
	0xf7, 0xb2, 0x94, 0x80, 0x1e, 0x9a, 0xbf, 0x0c, 0x18, 0x9d, 0xd8, 0xa2, 0x58, 0xf4, 0xf4, 0x0b,
	0x92, 0x92, 0xd8, 0xc0, 0xe1, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x76, 0xda, 0x7d, 0x0c,
	0x73, 0x01, 0x00, 0x00,
}
